title: [Windchasers Raid Guides]
description: [This is a hub for Destiny 2 raid guides produced by Windchasers clan members.]

remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one